export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
import MainContainer from '@/components/MainContainer';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
